Updated readme formatting and grammar to (hopefully) increase clarity
peroper/GlobalForester-API pull request #6
Opened 2022-10-28 12:24 UTC by maxkvelland2xper

2022-10-28 14:16 UTC, axeku requested changes

2022-10-28 14:16 UTC, axeku commented on README.md
> +- .shx - a register making reading the other files quicker.
varför komma istället för bindesträck för dbf?

2022-10-28 14:16 UTC, axeku commented on README.md
> +-t or --teamId, the ID of the Team you want to upload your Projects to.
Dessa flaggor är inte i en punktlista

2022-10-31 06:51 UTC, maxkvelland2xper commented on README.md
> +3. Move the _Swagger/swagger_client_ folder to _GlobalForester-API_.
Håller med, uppdaterat.

Ang. namngivningen så stämmer det förstås att man kan döpa den till vadsomhelst. Tyckte dock att det var tydligare att skriva default-namnet snarare än något vagare som "the root directory of your project" t.ex. Eller är det bättre?

2022-10-31 08:24 UTC, axeku commented on README.md
> +3. Move the _Swagger/swagger_client_ folder to _GlobalForester-API_.
Nä nått sånt där vagt blir ju inte bättre. Vi kan nog lämna det som det är

2022-10-31 08:56 UTC, axeku approved these changes

2022-10-31 13:25 UTC, larsabrasha requested changes

2022-10-31 13:25 UTC, larsabrasha commented on README.md
> +# Global Forester API Example Scripts
I have made som suggestions here: https://github.com/peroper/GlobalForester-API/pull/7

2022-10-31 15:23 UTC, larsabrasha approved these changes

2022-11-01 07:07 UTC, merged